<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b5d9b86b-fbde-41d1-997e-1bee0502f674</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnterpriseManagement.Application\EnterpriseManagement.Application.csproj" />
    <ProjectReference Include="..\EnterpriseManagement.Shared\EnterpriseManagement.Shared.csproj" />
    <ProjectReference Include="..\EnterpriseManagement.Infrastructure\EnterpriseManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
